### ISSUE TITLE
incompatibility with the curio of unying mod

### ISSUE THREAD

**Issue by AoSpirit** [blay09/HardcoreRevival#49] opened 2021-04-17 02:21 UTC
When you die with an immortality totem placed in its respective slot of the Curios and Curio of undying mods, the game crashes and you cannot exit  the /kill command is executed.

**Comment by BlayTheNinth** [comment] 2021-04-18 09:36
need crashlog

**Comment by AoSpirit** [comment] 2021-04-25 13:23
sorry I did not express myself well. The game does not crash, it just buggies. The animation of the resurrection totem occurs behind the revive screen and it is seen that you are already resurrected behind the menu, but if you give it to revive you get stuck in some kind of spectator mode where you can't move. I thought that it could be an incompatibility with other mods so I was eliminating all those that had relation with the death system like Corps mod, but I saw that the problem was related to the mod that I mentioned in the first message.Maybe other mods that use the resurrection method like the totem suffer the same inconvenience by not removing the death menu. I hope I have been helpful

**Comment by winsrp** [comment] 2021-05-10 19:38
same happened to me. 

The mod "Curio of Undying" which lets you put a totem in a curio slot, bugs out when you get killed and revived.

**Comment by BlayTheNinth** [comment] 2021-05-29 17:55
Duplicate of #43

**Closed as completed by BlayTheNinth** 2021-05-29 17:55 UTC
Labels: Bug, Duplicate, Crash
