### ISSUE TITLE
Showing KO screen after death in survival

### ISSUE THREAD

**Issue by GodOfWar6294** [blay09/HardcoreRevival#35] opened 2020-04-20 12:55 UTC
Whenever i die with this mod installed in survival, it brings me to the KO screen and the accept your fate button doesn't work. Please fix this or you leave my no choice but to delete this mod and publicly say that this mod doesn't work>.

I love the concept though xD

P.S. The versions of forge and minecraft match the mod

**Comment by GodOfWar6294** [comment] 2020-04-20 12:56
Also, keep making 1.15.2 mc and 31.1.0 forge mods!
I especially love the waystones, however, in a superflat world they generate a random name.

**Comment by BlayTheNinth** [comment] 2020-04-23 13:45
Duplicate of #34

**Closed as completed by BlayTheNinth** 2020-04-23 13:45 UTC
Labels: Feature, Duplicate
